import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer";
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Geist+Mono:wght@100..900&family=Geist:wght@100..900&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`font-geist antialiased max-w-4xl mx-auto px-4 pt-8 pb-4 bg-[#FEFEFF]`}
      >
        <Toaster richColors />
        {children}
        <Footer />
      </body>
    </html>
  );
}
